name: Keystore Oluştur

on:
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Keystore oluştur
        run: |
          keytool -genkey -v -keystore release-key.jks \
            -alias ioz-key -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "SifreniBuraya123!" \
            -keypass "SifreniBuraya123!" \
            -dname "CN=Ioz, OU=Ioz, O=Ioz, L=Istanbul, S=Istanbul, C=TR"

      - name: Base64'e çevir
        run: base64 -w 0 release-key.jks > keystore-base64.txt

      - name: Dosyaları yükle
        uses: actions/upload-artifact@v4
        with:
          name: keystore-dosyalari
          path: |
            release-key.jks
            keystore-base64.txt
